### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by AntiWarforever** [loguru-log/tonxdao_bot#6]
Activating virtual environment...
Starting the bot...

████████╗ ██████╗ ███╗   ██╗██╗  ██╗██████╗  █████╗  ██████╗
╚══██╔══╝██╔═══██╗████╗  ██║╚██╗██╔╝██╔══██╗██╔══██╗██╔═══██╗
   ██║   ██║   ██║██╔██╗ ██║ ╚███╔╝ ██║  ██║███████║██║   ██║
   ██║   ██║   ██║██║╚██╗██║ ██╔██╗ ██║  ██║██╔══██║██║   ██║
   ██║   ╚██████╔╝██║ ╚████║██╔╝ ██╗██████╔╝██║  ██║╚██████╔╝
   ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝ ╚═════╝

Select an action:

    1. Run clicker
    2. Create session
`
> 2024-10-29 21:02:37 | INFO | All sessions completed. Sleeping for 4.97 hours before restarting.`

**Comment by mohammad5806** [comment]
you need to make dao_sessions/dao_1 directory and paste your sessions in there then run the bot .
